### ISSUE TITLE
meta-genotypes table display

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1683]
![meta genotypes](https://user-images.githubusercontent.com/7359272/48489912-0c6d0600-e81c-11e8-9e49-351f8d8c7a48.jpg)

- [ ] there seems to be a lot of blank space at the bottom of these tables. Can this be removed?

**Comment by ValWood** [comment]
- [ ]  text of phenotype annotation is currently
 "Start a pathogen-host interaction phenotype annotation"
Suggest:
"Annotate pathogen-host interaction phenotype"

**Comment by ValWood** [comment]
- [ ] I have a feeling that in the instruction links to the right of the table the text on the 2nd and 3rd rows is very slightly larger. Or maybe it is a slightly different font.  It's odd it doesn't see to be a full point size but I'm sure there's a small difference?

**Comment by jseager7** [comment]
> I have a feeling that in the instruction links to the right of the table the text on the 2nd and 3rd rows is very slightly larger.

It is, and the larger text is wrong. I've opened a pull request #1689 to fix all these issues, and I'll tick them off here as they're completed.

**Comment by jseager7** [comment]
> there seems to be a lot of blank space at the bottom of these tables.

I think part of the reason you're seeing all that empty space is because the organism strains aren't being displayed. They're supposed to be shown underneath the binomial name, like this:

![mg_table_strains](https://user-images.githubusercontent.com/37659591/48549280-3deedb80-e8c7-11e8-8d16-160a21cbbf46.PNG)

But in your case, since no strains are found, they're just replaced by a hyphen. This happens for _Arabidopsis thaliana_ in my case too, even though the constituent host genotype has a strain. I suspect this is related to the fact I had to add a custom strain (_cv. Corsacalla-1_) instead of picking a strain from the pre-populated list. This problem might be covered by #1684.

**Comment by ValWood** [comment]
Ah OK. 

note that each Organism/Strain n combo needs to have it's own genotype row, because you need to be able to add annotations to individual  metagenotype/strain combos

**Comment by jseager7** [comment]
> you need to be able to add annotations to individual metagenotype/strain combos

I think this is handled by the fact that when a metagenotype is created, it gets the strain from the constituent genotypes &ndash; since we decided some time ago to bind the strain when the genotype is created, rather than binding it to the organism itself.

Every created metagenotype should get an individual row in the metagenotype table: I don't think there's any merging of rows when the organism is the same but the strain is different.

**Comment by jseager7** [comment]
Just fixed a bug from when I included 'phenotype' in the link text, even though it was already in the annotation name. The fix is here: https://github.com/pombase/canto/commit/99c383fdb20fe93544c8e5530b15789d34c6f09c

**Comment by jseager7** [comment]
Closing and moving to new issue at #1702, since it covers the problem with the extra blank space in the metagenotype table.
