### ISSUE TITLE
PHI-Canto workflow improvements

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2043]
This is my first go using to set up genotypes. Overall the experience wasn't too bad, and one the genotypes are set up it's fairly smooth. However, I struggled quite a bit with the phenotype workflow  (trying to put myself in the shoes of a complete novice). There are quite a few points where the interface is very very confusing.

1.
--

From the genotypes management (single gene). It isn't really clear that you need to go to "metagenotype management" and create a metagenotype before you can make a pathogen host-interaction  phenotype annotation.

![how to do host pathogen](https://user-images.githubusercontent.com/7359272/65898145-ca53a100-e3a8-11e9-8c66-179b8646dfcd.jpg)

 a minor aside 
why  "delete or edit genes and organisms list"
and not "delete or edit genes and organisms"

**Comment by ValWood** [comment]
2.
--

From the genotypes management (single gene). It isn't really clear that you need to go to "metagenotype management" and create a metagenotype before you can make a pathogen host-interaction  phenotype annotation.

![how to do host pathogen](https://user-images.githubusercontent.com/7359272/65898145-ca53a100-e3a8-11e9-8c66-179b8646dfcd.jpg)

**Comment by ValWood** [comment]
I think this page is particularly confusing. There  is lots of unnecessary content here  when you first arrive.

![unclear ho to do metagenotype](https://user-images.githubusercontent.com/7359272/65898432-76958780-e3a9-11e9-817b-c08336dd35ad.jpg)

Do we really need all these empty headers displayed? Is this helpful?

**Comment by ValWood** [comment]
The most obvious action on this page is to create a new pathogen genotype ?

**Comment by jseager7** [comment]
### Point 1

> why "delete or edit genes and organisms list" and not "delete or edit genes and organisms"

I agree that this wording is awkward, I just never got around to asking what it should be changed to. I'll make that change.

### Point 2

> I find it very strange to see curation options but no phenotype curation options.

I'm not sure why there isn't a single allele phenotype link on this page &ndash; there's no reason why we couldn't include one.

As for multiple allele phenotypes, The PomBase version of Canto doesn't have a link to this in the curation type list; instead it has a link to Genotype Management above the genotype table:

![image](https://user-images.githubusercontent.com/37659591/65952123-4dbcd300-e439-11e9-963e-41be3cda6080.png)

For some reason, that link isn't there in pathogen-host mode.

If you'd rather have the genotype management link in a list with a heading (like how it appears on the summary page) then I can do that, but that removes the indication that the Genotype Management button provides (due to using a forward arrow) that Genotype Management is the next step in the workflow:

![image](https://user-images.githubusercontent.com/37659591/65952873-b9537000-e43a-11e9-861b-fc5f1d56cc5a.png)

- - -

Personally, it feels like we're dealing with two scenarios here: either **a)** the user goes to the gene page expecting to assemble a genotype starting with that gene, or **b)** the user only wants to make a phenotype / annotation involving a single gene. I think it's going to be difficult to make the progression from gene to genotype in scenario (a) intuitive without risking confusing users who came to the page expecting scenario (b). I'll need to think more about this.

Also, note that the heading above the summary page gene list says '_Annotate_ genes', so it's likely that new users will assume that this page is used for annotations, rather than constructing genotypes.

### Point 3

> Do we really need all these empty headers displayed? Is this helpful?

Hiding the empty headers is something I wanted to do but never got round to. I'll fix this as soon as I can.

> The point that you are combining one pathogen and one host entry to make a metagenotype is completely lost.

I agree it's not obvious that you're trying to combine genotypes &ndash; and it won't be much more obvious even if we hide the headings &ndash; because we never once explain in the user interface what a metagenotype even is, so I think this page could benefit from some help text at least explaining the purpose of the interface.

> The most obvious action on this page is to create a new pathogen genotype ? (maybe this should be tucked more discreetly under the table "Add another pathogen genotype"

I could do this, but that might not make the action less obvious, because moving the link down the page would move it closer to the important action, which is the button to 'Make metagenotype'. I tried to reduce the emphasis of the genotype creation links by not styling them as buttons, but this clearly hasn't worked.

I think that 'Add another pathogen genotype' is better wording for the link though, since it implies some extra action, rather than something that is required for progression.

**Comment by jseager7** [comment]
### To-do

I'm listing the actions here that probably don't need any more discussion.

- [ ] Amend 'Delete or edit genes and organisms list' link text
- [ ] Hide empty sections on the Metagenotype Management page
- [ ] Add a 'Single allele phenotype' link on the gene curation page
- [ ] Amend genotype creation link text (Metagenotype Management)

**Comment by ValWood** [comment]
I chatted with @kimrutherford  about these this morning. I will pitch some suggestions later (not today, unfortunately). We can discuss them on the next call (or sooner if they make sense).

**Comment by ValWood** [comment]
I think there are some very minimal changes we can make to wording and ordering which might make things clearer. I'll mock these up.

**Comment by ValWood** [comment]
Thanks James. You can close this ticket.

I think we really need to think about how to make some of the actions clearer. I will open tickets if I have any simple ideas.

**Comment by jseager7** [comment]
Okay, I'll set the pull request to close this issue, so it will close automatically once @kimrutherford has reviewed and merged the changes.
